[2018-02-20 12:31:13] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:08:09] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:11:50] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:15] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:15] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:15] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:15] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:16] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:16] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:32] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:12:58] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/web/prod/dynamic/var/sessions/prod"" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/web/prod/dynamic/var/sessions/prod\" at /home/web/prod/dynamic/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2018-02-20 14:15:41] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:15:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:15:41] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:15:43] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:15:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:15:43] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:20:23] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:20:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:20:23] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:20:23] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:20:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:20:23] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:20:24] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:20:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:20:24] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:20:24] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:20:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:20:24] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:24:27] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:24:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:24:27] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:24:27] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:24:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:24:27] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:24:28] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:24:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:24:28] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:24:28] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:24:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:24:28] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:24:28] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:24:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:24:28] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:24:28] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:24:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:24:28] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:26:31] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:26:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:26:31] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:27:59] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:27:59] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:27:59] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:28:06] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:28:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:28:06] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:29:22] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:29:22] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:29:22] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
[2018-02-20 14:30:19] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\Web\\WebController::indexAction","_route":"homepage"},"request_uri":"http://dynamic.xlwlx.fr/","method":"GET"} []
[2018-02-20 14:30:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-02-20 14:30:19] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_security_login" as such route does not exist.")." at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig line 18 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist.\"). at /home/web/prod/dynamic/app/Resources/views/default/index.html.twig:18, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"fos_user_security_login\" as such route does not exist. at /home/web/prod/dynamic/var/cache/prod/appProdProjectContainerUrlGenerator.php:30)"} []
